<?php
// Script dependencies for index.js (normally generated by a build step).
return array(
	'dependencies' => array( 'wp-block-editor', 'wp-blocks', 'wp-components', 'wp-data', 'wp-element', 'wp-i18n', 'wp-server-side-render' ),
	'version'      => FORKPOSTER_VERSION,
);
